### ISSUE TITLE
Integrate the stellar-wallets-kit package

### ISSUE THREAD

**Issue by ElliotFriend** [stellar/basic-payment-app#17]
The [`stellar-wallets-kit` package](https://stellarwalletskit.dev/) can abstract the work of integrating various Stellar wallets into an application. We should provide users the option to sign up and/or sign in with a wallet, using this package.

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue @ElliotFriend

**Comment by BernalHQ** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hi, my name is Bernal, and I’m a software developer with four years of experience. I’m passionate about contributing to projects and learn, and I would love the opportunity to contribute to this project

### How I plan on tackling this issue
The first step is to understand the project and how it works. Once I have a good understanding of it, I’ll propose a solution to the issue. After that, I’ll implement the solution and run some tests to ensure everything works correctly.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here. Here's a link to my profile https://app.onlydust.com/u/raizo07

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I am a blockchain developer . please i will like to work on this issue

### How I plan on tackling this issue
To approach this problem i will do the following :

1.Integrate stellar-wallets-kit Install and import the package into your application.
2. Create Sign Up/Sign In Function: Implement functions that use the package to handle wallet-based authentication for users.
3.UI Implementation: Design and add UI components for users to select their wallet and initiate the sign-up/sign-in process.
4. Test: Ensure that users can successfully sign up and sign in using their wallets without errors.

**Comment by thesledge04** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I have experience in integrating blockchain technologies and wallet functionalities into applications. My knowledge of the Stellar ecosystem, combined with familiarity in working with wallet integration packages like stellar-wallets-kit, allows me to efficiently implement user sign-up and sign-in processes using various Stellar wallets.

### How I plan on tackling this issue
Review the stellar-wallets-kit functionalities.
Design the UI for sign-up/sign-in.
Integrate wallet authentication methods.
Provide user feedback during the process.
Test across different wallets for functionality.
Document the implementation for clarity.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
I have experience on full stack development building an EVM explorer and indexer: https://github.com/walnuthq/op-scan


### How I plan on tackling this issue
I will make sure to integrate this package in the project to allow any wallet connection.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/basic-payment-app).

### My background and how it can be leveraged
Hello @ElliotFriend I am Joseph I am a Software developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. 

### How I plan on tackling this issue
To fix this, I will integrate the stellar-wallets-kit package into the application. This will abstract the process of handling various Stellar wallets. I'll then update the authentication flow to provide users with the option to sign up or sign in using their wallets, leveraging the package’s built-in functions for wallet management and authentication. Finally, I will test the integration to ensure users can seamlessly connect and authenticate with their Stellar wallets
